### ISSUE TITLE
clone后的项目无法构建。

### ISSUE THREAD

**Issue by ilumer** [daquexian/chaoli-forum-for-android-2#1]
clone后的项目无法导入到`Android Studio`中，在手动下载了`gradle2.2`后还是没有办法正常的导入项目（我对`gradle`并不熟悉）。终端中运行`./gradlew`后也是卡在了` Configuring > 0/2 projects > root project `时，请问应该如何导入工程。`Android studio`上的报错信息显示缺少`build system`.

**Comment by daquexian** [comment]
哇，第一个issue。不知道是不是网络原因(某个神秘的墙)导致第三方库下载不下来？我对这方面也没有太多经验。。可以贴一下详细的错误信息吗

**Comment by ilumer** [comment]
长时间的`Sync`后，我stop了。提示我无法`sync` `gradle-2.14.1`.但是我自己的项目是可以很快的`sync`的同样的是2.14.1版本。完全不知道哪里有问题。ps(提交一个google play 上的bug 就是的在没有登录的情况下是关注和发帖等行为都会崩溃)

**Comment by daquexian** [comment]
唔。。有给Gradle设置代理吗(它和AS用的是不同的代理，要单独设置

**Comment by daquexian** [comment]
谢谢乃的bug~~最近在忙考试没有时间更新，下一版就解决~~

**Comment by ilumer** [comment]
在尝试了多种方法失败后，换了文件夹重新`clone`后就可以了快速`build`了(之前我就clone了两个项目，不知道是不是这个原因)。常用的解决方法http://stackoverflow.com/questions/27589336/android-studio-update-errorcould-not-run-build-action-using-gradle-distributio。 话说pr有什么要求吗？

**Comment by daquexian** [comment]
要求的话。。大括号不换行？暂时想不起来什么。。设计方面要遵循MD
要改动哪里的话可以先在这里说一下~我来看看是不是当时因为什么坑才用了不好的写法，以免踩坑

**Comment by daquexian** [comment]
另外架构是MVVM架构，关于其中的ViewModel层对View层的控制我有个自己的一套方法(就是给ObserverableXX对象添加监听器的那个)，最好是沿用这个方法(比较纯粹的数据驱动)。另外虽然现在ViewModel里暂时没有持有Context或者Activity的引用，但是我现在发现其实没必要遵循这个要求，只要持有的是基类就好。
